import React, { useState, useEffect } from "react";
import { Sparkles, RotateCw, AlertCircle } from "lucide-react";
import { Project, InboundRevenue, DailyPayment, OfficeExpense, Vendor } from "../types";

interface DashboardSummaryCardProps {
  projects: Project[];
  inboundRevenues: InboundRevenue[];
  dailyPayments: DailyPayment[];
  officeExpenses: OfficeExpense[];
  vendors: Vendor[];
}

export default function DashboardSummaryCard({
  projects,
  inboundRevenues,
  dailyPayments,
  officeExpenses,
  vendors,
}: DashboardSummaryCardProps) {
  const [summary, setSummary] = useState<string>("");
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);
  const [isRefreshing, setIsRefreshing] = useState<boolean>(false);

  const fetchSummary = async (showRefreshState = false) => {
    if (showRefreshState) {
      setIsRefreshing(true);
    } else {
      setLoading(true);
    }
    setError(null);

    try {
      const response = await fetch("/api/ai/dashboard-summary", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          projects,
          inbound_revenues: inboundRevenues,
          daily_payments: dailyPayments,
          office_expenses: officeExpenses,
          vendors,
        }),
      });

      if (!response.ok) {
        throw new Error(`Failed to fetch AI Summary: ${response.statusText}`);
      }

      const data = await response.json();
      setSummary(data.summary);
    } catch (err: any) {
      console.error("Failed to generate dashboard summary:", err);
      setError(err.message || "Something went wrong while generating the summary.");
    } finally {
      setLoading(false);
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    fetchSummary();
  }, [projects, inboundRevenues, dailyPayments, officeExpenses, vendors]);

  return (
    <div id="ai-summary-card" className="bg-gradient-to-br from-indigo-950 via-slate-900 to-slate-950 border border-slate-800 rounded-2xl p-5 text-white shadow-lg space-y-4 relative overflow-hidden">
      {/* Decorative background light */}
      <div className="absolute top-0 right-0 w-48 h-48 bg-indigo-500/10 rounded-full blur-3xl pointer-events-none" />
      
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="bg-indigo-500/20 text-indigo-400 p-1.5 rounded-lg border border-indigo-500/30">
            <Sparkles className="w-4 h-4 animate-pulse text-indigo-300" />
          </div>
          <div>
            <h3 className="text-sm font-bold tracking-tight text-white flex items-center gap-1.5">
              AI Executive Briefing
              <span className="text-[10px] bg-indigo-500/30 text-indigo-200 px-1.5 py-0.5 rounded font-black tracking-widest uppercase">
                Beta
              </span>
            </h3>
            <p className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider">
              Real-time Portfolio Analysis
            </p>
          </div>
        </div>

        <button
          id="ai-summary-refresh-btn"
          onClick={() => fetchSummary(true)}
          disabled={loading || isRefreshing}
          className="p-1.5 hover:bg-slate-800 text-slate-400 hover:text-indigo-400 rounded-lg transition-colors border border-transparent hover:border-slate-700 disabled:opacity-50"
          title="Refresh AI Summary"
        >
          <RotateCw className={`w-4 h-4 ${isRefreshing ? "animate-spin text-indigo-400" : ""}`} />
        </button>
      </div>

      {loading ? (
        <div className="space-y-2 py-2">
          <div className="h-4 bg-slate-800/80 rounded-md animate-pulse w-full" />
          <div className="h-4 bg-slate-800/80 rounded-md animate-pulse w-11/12" />
          <div className="h-4 bg-slate-800/80 rounded-md animate-pulse w-10/12" />
        </div>
      ) : error ? (
        <div className="flex items-start gap-2 text-rose-400 bg-rose-500/10 border border-rose-500/20 p-3 rounded-lg text-xs leading-relaxed">
          <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <p className="font-bold">Summary Unavailable</p>
            <p className="text-rose-300/80 font-medium">{error}</p>
          </div>
        </div>
      ) : (
        <div className="space-y-2">
          <p className="text-sm text-slate-200 leading-relaxed font-medium font-sans">
            {summary}
          </p>
        </div>
      )}

      <div className="pt-2 border-t border-slate-800/50 flex justify-between items-center text-[10px] text-slate-500 font-semibold uppercase tracking-wider">
        <span>Karam AI Engine v1.2</span>
        <span className="text-slate-500">Generated by AI — verify before use</span>
      </div>
    </div>
  );
}
